
version: "3.9"
services:
  prerender:
    build: .
    restart: unless-stopped
    environment:
      - CACHE_MAXSIZE=10000
      - CACHE_TTL=604800
    deploy:
      replicas: 3
    logging:
      options:
        max-size: 50m
    ports:
      - "3000-3002:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/https://www.google.com"]
      interval: 1h
      timeout: 20s
      retries: 2
      start_period: 5s